name: .NET

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore MinimalChat.API/MinimalChat.API.csproj

      - name: Build
        run: dotnet build MinimalChat.API/MinimalChat.API.csproj --no-restore

      - name: Publish
        run: dotnet publish MinimalChat.API/MinimalChat.API.csproj --configuration Release --output ./publish

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "minimalchat"
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
